version: "2"
services:
  app:
    image: jc21/registry-ui
    ports:
      - 80:80
    environment:
      - REGISTRY_HOST=127.0.0.1:5000
      - REGISTRY_SSL=false
      - REGISTRY_DOMAIN=127.0.0.1:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=
      - REGISTRY_USER=
      - REGISTRY_PASS=
    restart: on-failure
    network_mode: "host"

